services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: "<Add_your_MongoDbUrl>"
    volumes:
      - ./server:/app
    command: npm run start

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: npm run start
